services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
      - ANTHROPIC_API_KEY
      - BEDROCK_BEARER_TOKEN
    ports:
      - 1972
      - "8080:52773"
      - 53773
    volumes:
      - ./:/home/irisowner/dev
      - "C:\\Users\\xwu\\Downloads:/keys"
    command: ["-k", "/keys/iris-container-x64.key"]
